modules/Mygovo/Http/routes.php
<?php

$lang = null;
$locale = Request::segment(1);
if (in_array($locale, Config::get('app.locales'))) {
    \Lang::setLocale($locale);
    \Carbon\Carbon::setLocale($locale);
    $lang = $locale;
}

Route::group(
    ['prefix' => $lang, 'namespace' => 'Modules\\Mygovo\\Http\\Controllers'],
    function (\Illuminate\Routing\Router $router) {

        $router->group(
            [
                'prefix' => 'services',
                'where'  => [
                    'id'           => '\d+',
                    'service'      => '\d+',
                    'slug'         => '[a-z0-9-_]+',
                    'service_slug' => '[a-z0-9-_]+',
                    'category'     => '[a-z0-9-_]+'
                ]
            ],
            function (\Illuminate\Routing\Router $router) {
                $router->get('{category}/{service}{service_slug?}', 'MygovoController@service');
                $router->get('{id}{slug?}', 'MygovoController@services');
                $router->get('/', 'MygovoController@servicesMain');
            }
        );


        $router->group(
            [
                'prefix' => 'blog',
                'where'  => [
                    'id'   => '\d+',
                    'slug' => '[a-z0-9-_]+',
                ]
            ],
            function (\Illuminate\Routing\Router $router) {
                $router->get('{id}{slug?}', 'MygovoController@newsItem');
                $router->get('', 'MygovoController@news');
            }
        );

        $router->group(
            [
                'prefix' => 'catalog',
                'where'  => [
                    'id'           => '\d+',
                    'slug'         => '[a-z0-9-_]+',
                    'product_id'   => '\d+',
                    'product_slug' => '[a-z0-9-_]+'
                ]
            ],
            function (\Illuminate\Routing\Router $router) {
                $router->get('{id}{slug?}/{product_id}{product_slug?}', 'MygovoController@catalogProduct');
                $router->get('{id}{slug?}', 'MygovoController@catalogCategory');
                $router->get('', 'MygovoController@catalog');
            }
        );

        $router->get('certificates', ['as' => 'mygovo.certificates', 'uses' => 'MygovoController@certificates']);
        $router->get('contacts', ['as' => 'mygovo.contacts', 'uses' => 'MygovoController@contacts']);
        $router->post('submit', ['as' => 'mygovo.submit', 'uses' => 'MygovoController@submitForm']);
        $router->get('/', ['as' => 'mygovo.index', 'uses' => 'MygovoController@index']);
        //0$router->get('gallery', ['as' => 'mygovo.gallery', 'uses' => 'MygovoController@gallery']);
        $router->get('gallery', 'MygovoController@gallery');
    }
);

modules/Mygovo/Http/Controllers/Backend/Achievements.php
<?php namespace Modules\Mygovo\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Modules\Backend\Http\Controllers\BaseController;
use Modules\Backend\Support\Metronic;
use Modules\Mygovo\Models\Achievement as AchievementModel;

class Achievements extends BaseController
{
    public function __construct()
    {
        parent::__construct();

        Metronic::module(['datatable']);
        Metronic::menu('achievements');
    }

    public function getIndex()
    {
        $data = AchievementModel::query()
            ->get();

        return \View::make('mygovo::backend.achievements.index', ['data' => $data]);
    }

    public function postIndex(Request $request)
    {
        foreach ($request->input('content', []) as $id => $data) {
            $model = AchievementModel::query()
                ->findOrFail($id);

            $model->fill($data);
            $model->save();
        }

        return \Redirect::route('backend.mygovo.achievements.index')
            ->with('message', 'success');
    }
}

modules/Mygovo/Http/Controllers/Backend/Banners.php
<?php namespace Modules\Mygovo\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Backend\Support\Metronic;
use Modules\Mygovo\Models\Banner;

class Banners extends Controller
{
    public function __construct()
    {
        Metronic::module('colorbox');

        Metronic::menu('banners');
    }

    public function getIndex()
    {
        $data = Banner::query()
            ->orderBy('id', 'asc')
            ->get();

        return \View::make('mygovo::backend.banners.index', ['banners' => $data]);
    }

    public function postIndex(Request $request)
    {
        foreach ($request->input('data', []) as $id => $data) {
            $model = Banner::query()
                ->findOrFail($id);

            $model->fill($data);
            $model->save();
        }

        return \Redirect::route('backend.mygovo.banners.index');
    }
}

modules/Mygovo/Http/Controllers/Backend/Card.php
<?php namespace Modules\Mygovo\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Modules\Backend\Http\Controllers\BaseController;
use Modules\Backend\Support\Metronic;
use Modules\Media\Models\Media as MediaModel;
use Modules\Mygovo\Models\Certificate;

class Card extends BaseController
{
    public function __construct()
    {
        parent::__construct();

        Metronic::menu('certificates', 'card');
        Metronic::module(['ckeditor', 'colorbox']);
    }

    public function getIndex()
    {
        $data = Certificate::query()
            ->where('type', '=', 'card')
            ->first();

        $text = $data->texts->keyBy('lang')->toArray();

        return \View::make('mygovo::backend.card.index', ['data' => $data, 'text' => $text]);
    }

    public function postIndex(Request $request)
    {
        return \DB::transaction(
            function () use ($request) {
                $model = Certificate::query()
                    ->where('type', '=', 'card')
                    ->firstOrFail();

                $image = MediaModel::search($request->input('media_path'));
                $data['media_id'] = ($image) ? $image->id : null;

                $model->fill($data);
                $model->save();

                foreach ($request->input('text', []) as $lang => $data) {
                    $text = Certificate\Text::firstOrNew(['certificate_id' => $model->id, 'lang' => $lang]);
                    $text->fill($data);
                    $text->save();
                }

                return \Redirect::route('backend.mygovo.card.index')
                    ->with('message', 'success');
            }
        );
    }
}

modules/Mygovo/Http/Controllers/Backend/Catalog.php
<?php namespace Modules\Mygovo\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Modules\Backend\Http\Controllers\BaseController;
use Modules\Backend\Support\Metronic;
use Modules\Mygovo\Models\Category;
use Modules\Mygovo\Models\CategoryText;

class Catalog extends BaseController
{
    public function __construct()
    {
        parent::__construct();

        Metronic::module(['datatable']);
        Metronic::menu('catalog', 'categories');
    }

    public function getIndex()
    {
        return \View::make('mygovo::backend.catalog.categories.index');
    }

    public function postIndex(Request $request)
    {
        $model = Category::query();
        $recordsTotal = $recordsFiltered = $model->count();

        $model->limit($request->input('length', 25))
            ->offset($request->input('start', 0));

        $model->orderBy('created_at', 'desc');

        $collection = $model->get();

        $data = [];
        foreach ($collection as $item) {
            $data[] = [
                $item->text->caption,
                '<a href="'.route('backend.mygovo.catalog.status', ['id' => $item->id]).'" rel="item-status" class="btn btn-sm '.($item->active ? 'green' : 'red').'"><i class="fa '.($item->active ? 'fa-check' : 'fa-ban').'"></i></a>',
                '<a href="'.route('backend.mygovo.catalog.edit', ['id' => $item->id]).'" class="btn btn-sm green" title="Редагувати"><i class="fa fa-pencil"></i></a> '.
                '<a href="'.route('backend.mygovo.catalog.destroy', ['id' => $item->id]).'" rel="item-destroy" class="btn btn-sm red" title="Видалит"><i class="fa fa-trash-o"></i></a>'
            ];
        }

        return [
            'data'            => $data,
            'recordsTotal'    => $recordsTotal,
            'recordsFiltered' => $recordsFiltered
        ];
    }

    public function getCreate()
    {
        return \View::make('mygovo::backend.catalog.categories.form');
    }

    public function postCreate(Request $request)
    {
        $model = new Category();

        return $this->save($model, $request);
    }

    public function getEdit($id)
    {
        $data = Category::query()
            ->findOrFail($id);

        $text = $data->texts->keyBy('lang')->toArray();

        return \View::make('mygovo::backend.catalog.categories.form', ['data' => $data, 'text' => $text]);
    }

    public function postEdit($id, Request $request)
    {
        /**
         * @var Category $model
         */
        $model = Category::query()
            ->findOrFail($id);

        return $this->save($model, $request);
    }

    public function anyDestroy($id)
    {
        Category::query()
            ->findOrFail($id)
            ->delete();

        return \Redirect::route('backend.mygovo.catalog.index');
    }

    public function anyStatus($id)
    {
        $model = Category::query()
            ->findOrFail($id);

        $model->active = ($model->active == 1) ? 0 : 1;
        $model->save();

        return $model->active;
    }

    private function save(Category $model, Request $request)
    {
        return \DB::transaction(
            function () use ($model, $request) {
                $data = $request->input('content', []);

                $slug = empty($data['slug']) ? Str::slug($request->input('text.uk.caption')) : Str::slug($data['slug']);
                $data['slug'] = strtolower($slug);

                $model->fill($data);
                $model->save();

                foreach ($request->input('text', []) as $lang => $data) {
                    $text = CategoryText::firstOrNew(['category_id' => $model->id, 'lang' => $lang]);
                    $text->fill($data);
                    $text->save();
                }

                return \Redirect::route('backend.mygovo.catalog.edit', ['id' => $model->id])
                    ->with('message', 'success');
            }
        );
    }
}

modules/Mygovo/Http/Controllers/Backend/Categories.php
<?php namespace Modules\Mygovo\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Modules\Backend\Http\Controllers\BaseController;
use Modules\Backend\Support\Metronic;
use Modules\Media\Models\Media as MediaModel;
use Modules\Mygovo\Models\Service\Category as ServiceCategoryModel;
use Modules\Mygovo\Models\Service\Text as ServiceTextModel;

class Categories extends BaseController
{
    public function __construct()
    {
        parent::__construct();

        Metronic::module(['datatable', 'colorbox']);
        Metronic::menu('services', 'categories');
    }

    public function getIndex()
    {
        $data = ServiceCategoryModel::query()
            ->with(['text'])
            ->orderBy('weight', 'asc')
            ->orderBy('created_at', 'desc')
            ->get();

        return \View::make('mygovo::backend.services.categories.index', ['data' => $data]);
    }

    public function getCreate()
    {
        return \View::make('mygovo::backend.services.categories.edit');
    }

    public function postCreate(Request $request)
    {
        $model = new ServiceCategoryModel();

        return $this->save($model, $request);
    }

    public function getEdit($id)
    {
        $data = ServiceCategoryModel::query()
            ->findOrFail($id);

        $text = $data->texts->keyBy('lang')->toArray();

        return \View::make('mygovo::backend.services.categories.edit', ['data' => $data, 'text' => $text]);
    }

    public function postEdit($id, Request $request)
    {
        /**
         * @var ServiceCategoryModel $model
         */
        $model = ServiceCategoryModel::query()
            ->findOrFail($id);

        return $this->save($model, $request);
    }

    public function anyDestroy($id)
    {
        ServiceCategoryModel::query()
            ->findOrFail($id)
            ->delete();

        return \Redirect::route('backend.mygovo.categories.index');
    }

    public function anyStatus($id)
    {
        $model = ServiceCategoryModel::query()
            ->findOrFail($id);

        $model->active = ($model->active == 1) ? 0 : 1;
        $model->save();

        return $model->active;
    }

    public function anyWeight(Request $request)
    {
        $list = $request->input('list', []);

        foreach ($list as $weight => $id) {
            ServiceCategoryModel::query()
                ->where('id', '=', $id)
                ->update(['weight' => $weight]);
        }
    }

    private function save(ServiceCategoryModel $model, Request $request)
    {
        return \DB::transaction(
            function () use ($model, $request) {
                $data = $request->input('content', []);

                $image = MediaModel::search($request->input('media_path'));
                $data['media_id'] = ($image) ? $image->id : null;
                $slug = empty($data['slug']) ? Str::slug($request->input('text.uk.caption')) : Str::slug($data['slug']);
                $data['slug'] = strtolower($slug);

                $model->fill($data);
                $model->save();

                foreach ($request->input('text', []) as $lang => $data) {
                    $text = ServiceTextModel::firstOrNew(['category_id' => $model->id, 'lang' => $lang]);
                    $text->fill($data);
                    $text->save();
                }

                return \Redirect::route('backend.mygovo.categories.edit', ['id' => $model->id])
                    ->with('message', 'success');
            }
        );
    }
}

modules/Mygovo/Http/Controllers/Backend/Certificates.php
<?php namespace Modules\Mygovo\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Modules\Backend\Http\Controllers\BaseController;
use Modules\Backend\Support\Metronic;
use Modules\Mygovo\Models\Certificate;

class Certificates extends BaseController
{
    public function __construct()
    {
        parent::__construct();

        Metronic::module('ckeditor');
        Metronic::menu('certificates', 'items');
    }

    public function getIndex()
    {
        $data = Certificate::query()
            ->where('type', '=', 'certificate')
            ->get();

        return \View::make('mygovo::backend.certificates.index', ['data' => $data]);
    }

    public function getEdit($id)
    {
        $data = Certificate::query()
            ->where('type', '=', 'certificate')
            ->findOrFail($id);

        $text = $data->texts->keyBy('lang')->toArray();

        return \View::make('mygovo::backend.certificates.edit', ['data' => $data, 'text' => $text]);
    }

    public function postEdit($id, Request $request)
    {
        return \DB::transaction(
            function () use ($id, $request) {
                $model = Certificate::query()
                    ->where('type', '=', 'certificate')
                    ->findOrFail($id);

                foreach ($request->input('text', []) as $lang => $data) {
                    $text = Certificate\Text::firstOrNew(['certificate_id' => $model->id, 'lang' => $lang]);
                    $text->fill($data);
                    $text->save();
                }

                return \Redirect::route('backend.mygovo.certificates.edit', ['id' => $id])
                    ->with('message', 'success');
            }
        );
    }
}

modules/Mygovo/Http/Controllers/Backend/Gallery.php
<?php namespace Modules\Mygovo\Http\Controllers\Backend;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Backend\Support\Metronic;
use Modules\Mygovo\Models\Gallery as GalleryModel;

class Gallery extends Controller
{
    public function __construct()
    {
        Metronic::module(['colorbox']);

        Metronic::menu('gallery');
    }

    public function getIndex()
    {
        $data = GalleryModel::query()
            ->get();

        return \View::make('mygovo::backend.gallery.index', ['data' => $data]);
    }

    public function getEdit($id)
    {
        $data = GalleryModel::query()
            ->findOrFail($id);

        $template = $data->key == 'main' ? 'main-gallery' : 'edit';

        return \View::make('mygovo::backend.gallery.'.$template, ['data' => $data]);
    }

    public function postEdit($id, Request $request)
    {
        /**
         * @var GalleryModel $model
         */
        $model = GalleryModel::query()
            ->findOrFail($id);

        $model->images()->delete();
        $model->images()->createMany($request->input('gallery', []));

        return \Redirect::route('backend.mygovo.gallery.edit', ['id' => $model->id])
            ->with('message', 'success');
    }
}

modules/Mygovo/resources/views/backend/services/index.blade.php
@extends('backend::layouts.master')
@section('content')
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="portlet box blue-hoki base-portlet">
                <div class="portlet-title">
                    <div class="caption">Послуги</div>
                    <div class="actions">
                        <a class="btn btn-default btn-sm" rel="to-index"
                           href="{{URL::route('backend.mygovo.services.create')}}">
                            <i class="fa fa-plus"></i> Додати</a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-container">
                        <table class="table table-striped table-bordered table-hover"
                               data-url="{{URL::route('backend.mygovo.services.weight')}}">
                            <thead>
                            <tr class="heading">
                                <th>{{trans('backend::common.caption')}}</th>
                                <th width="40px">{{trans('backend::common.status')}}</th>
                                <th width="150px">{{trans('backend::common.actions')}}</th>
                            </tr>
                            </thead>
                            <tbody class="sortable">
                            @foreach($data as $item)
                                <tr data-id="{{$item->id}}">
                                    <td>{{$item->text->caption}}</td>
                                    <td>
                                        <a href="{{URL::route('backend.mygovo.services.status',['id' => $item->id])}}"
                                           rel="item-status" class="btn btn-sm {{$item->active ? 'green' : 'red'}}">
                                            <i class="fa {{$item->active ? 'fa-check' : 'fa-ban'}}"></i></a>
                                    </td>
                                    <td>
                                        <a href="{{URL::route('backend.mygovo.services.create').'?service_id='.$item->id}}"
                                           class="btn btn-sm default" title="Створити">
                                            <i class="fa fa-plus"></i></a>
                                        <a href="{{URL::route('backend.mygovo.services.edit', ['id' => $item->id])}}"
                                           rel="edit-portlet" class="btn btn-sm green" title="Редагувати">
                                            <i class="fa fa-pencil"></i></a>
                                        <a href="{{URL::route('backend.mygovo.services.destroy', ['id' => $item->id])}}"
                                           rel="item-destroy" class="btn btn-sm red" title="Видалити">
                                            <i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                                @if($item->childs)
                                    @foreach($item->childs as $child)
                                        <tr>
                                            <td style="padding-left: 35px;">{{$child->text->caption}}</td>
                                            <td>
                                                <a href="{{URL::route('backend.mygovo.services.status',['id' => $child->id])}}"
                                                   rel="item-status" class="btn btn-sm {{$child->active ? 'green' : 'red'}}">
                                                    <i class="fa {{$child->active ? 'fa-check' : 'fa-ban'}}"></i></a>
                                            </td>
                                            <td>
                                                <a href="{{URL::route('backend.mygovo.services.edit', ['id' => $child->id])}}"
                                                   rel="edit-portlet" class="btn btn-sm green" title="Редагувати">
                                                    <i class="fa fa-pencil"></i></a>
                                                <a href="{{URL::route('backend.mygovo.services.destroy', ['id' => $child->id])}}"
                                                   rel="item-destroy" class="btn btn-sm red" title="Видалити">
                                                    <i class="fa fa-trash-o"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('modules/mygovo/backend/js/services.js')}}"></script>
@endsection